{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinycyjs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinyCyJS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinyCyJS/shinyCyJS_{{ version }}.tar.gz
  sha256: c65bb019369ce4c7d096e3cadae15a2daa616e1d38bdc9411f613c1fcf94f9f5

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmlwidgets
  run:
    - r-base
    - r-htmlwidgets

test:
  commands:
    - $R -e "library('shinyCyJS')"           # [not win]
    - "\"%R%\" -e \"library('shinyCyJS')\""  # [win]

about:
  home: https://github.com/jhk0530/shinyCyJS
  license: MIT
  summary: Create Interactive Graph (Network) Visualizations. 'shinyCyJS' can be used in 'Shiny'
    apps or viewed from 'Rstudio' Viewer. 'shinyCyJS' includes API to build Graph model
    like node or edge with customized attributes for R. 'shinyCyJS' is built with 'cytoscape.js'
    and 'htmlwidgets' R package.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: shinyCyJS
# Title: Create Interactive Network Visualizations in R and 'shiny'
# Version: 1.0.0
# Authors@R: c( person("Jinhwan", "Kim", , email = "hwanistic@gmail.com", role = c("aut", "cre", "cph")) )
# Description: Create Interactive Graph (Network) Visualizations. 'shinyCyJS' can be used in 'Shiny' apps or viewed from 'Rstudio' Viewer. 'shinyCyJS' includes API to build Graph model like node or edge with customized attributes for R. 'shinyCyJS' is built with 'cytoscape.js' and 'htmlwidgets' R package.
# License: MIT + file LICENSE
# URL: https://github.com/jhk0530/shinyCyJS
# BugReports: https://github.com/jhk0530/shinyCyJS/issues
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Imports: htmlwidgets
# Suggests: testthat (>= 2.1.0), rmarkdown
# NeedsCompilation: no
# Packaged: 2023-09-26 01:56:42 UTC; jinhwan
# Author: Jinhwan Kim [aut, cre, cph]
# Maintainer: Jinhwan Kim <hwanistic@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-09-26 02:30:02 UTC
